site: Eigenbahn blog
url: eigenbahn.com
# host: 0.0.0.0
author: Jordan Besly
author:
  name: Jordan Besly
  email:
  url:
  avatar:
title: Eigenbahn blog
description: Various ramblings about technology & design
logo:
image:
#twitter: eigenbahn
#twitter:
#  username: eigenbahn
#  creator: eigenbahn
#  card: summary
social:
  name: Jordan Besly
  links:
    - https://twitter.com/#
    - https://www.dribbble.com/#
    - https://github.com/#
    - https://codepen.io/#

permalink: pretty

disqus:
  name: "your disqus username" # required
  noscript: "Please enable JavaScript to view the comments powered by Disqus." # optional

feed:
  categories:
    - emacs

baseurl:             ""

include:
  - _redirects

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - disqus-for-jekyll

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  - scope:
      path: "assets/images"
    values:
      image: true
